let FILE_NOT_FOUND="FILE NOT FOUND";
let DATA_ADDED="DATA ADDED";
let DATA_DELETED="DATA DELETED";
let DATA_UPDATED="DATA UPDATED";
let DATA_DISPLAYED="DATA DISPLAYED";
let NOT_VALID_EMPLOYEE_ID="Enter Valid Employee Id";
let NOT_UNIQUE_EMPLOYEE_ID="Enter Unique Employee Id";

let ERROR="ERROR";
let SUCCESS="SUCCESS";
module.exports={
    FILE_NOT_FOUND,DATA_ADDED,DATA_DELETED,DATA_UPDATED,DATA_DISPLAYED,ERROR,SUCCESS,NOT_VALID_EMPLOYEE_ID,NOT_UNIQUE_EMPLOYEE_ID
}

